vimc/orderly1

docker/build-ci.sh, docker/teamcity-demo.sh
=> i997: Lock short commits to 7 characters

R/runner.R
This replaces the stdout = "|" (pipe) with a plain file and seems to
eliminate the slowdown at least for my testing (see the issue for a
minimal example).
https://vimc.myjetbrains.com/youtrack/issue/VIMC-885
=> i885: Fix for the runner slowdown

.Rbuildignore, .gitignore, .travis.yml, DESCRIPTION, Makefile, R/util.R, R/vault.R, appveyor.yml, tests/testthat/helper-orderly.R, tests/testthat/test-util.R, update_web.sh
This should put the work in https://github.com/vimc/vaultr/pull/2 a bit more into context
=> i600 - use vaultr's new caching support

inst/orderly_example.yml, tests/testthat/test-z-runner.R
This is used by orderly::orderly_new and is incorrect
=> i1754 - Correct documentation

DESCRIPTION, NEWS.md, R/git.R, R/main.R, R/recipe_run.R, R/runner.R, man/orderly_run.Rd, tests/testthat/helper-orderly.R, tests/testthat/test-git.R, tests/testthat/test-main.R, tests/testthat/test-run.R, tests/testthat/test-z-runner.R, vignettes/orderly.Rmd, vignettes/src/orderly.R
This is a big ugly PR sorry - this resurrects ancient old work and adds a few bits to it.  It's also in a corner of the package that has seen less general use because it's never worked that well
See https://vimc.myjetbrains.com/youtrack/issue/VIMC-1793 for details.
=> I1793: improvements to the runner

docker/Dockerfile
There will be a chain of updates here as this flows through other containers.  This is the base one.
When the docker containers are updated you need to check teamcity to make sure they're building ok
=> i1800: Update to use R 3.5.0

R/recipe_read.R, tests/testthat/test-recipe-read.R
=> i1817: Fix unknown artrefact error message

NEWS.md, R/new.R, man/orderly_new.Rd, tests/testthat/test-new.R
See https://vimc.myjetbrains.com/youtrack/issue/VIMC-1877 for details and motivation
=> i1877: custom templates

DESCRIPTION, R/main.R, R/runner.R, inst/examples/interactive/src/count/orderly.yml, inst/examples/interactive/src/count/script.R, inst/examples/interactive/src/count_param/orderly.yml, inst/examples/interactive/src/count_param/script.R, tests/testthat/helper-orderly.R, tests/testthat/test-z-runner.R
These are particularly obnoxious to test - instructions will be included in the corresponding montagu-r PR
=> i1795: improvements to the orderly runner

DESCRIPTION, NEWS.md, R/remote_api.R
We never tested these changes with science!  So there are several issues.  Can you give this a try (will need to use the corresponding change in montagu-r too) https://github.com/vimc/montagu-r/pull/10
=> i1911: Fix remote check

docker/Dockerfile
wait for the TC build to pass, then this needs propagating through the other containers
=> i1917: Install RPostgres from CRAN

DESCRIPTION, R/recipe_run.R, man/orderly_cleanup.Rd, man/orderly_latest.Rd, man/orderly_run.Rd, man/orderly_run_remote.Rd, man/orderly_test_start.Rd
Just some small additions to the documentation that would have been useful when I wanted to remind myself how to use parameters.
=> small improvements to the documentation of orderly_run()

DESCRIPTION, NEWS.md, R/migrate.R, tests/testthat/test-orderly.R
https://vimc.myjetbrains.com/youtrack/issue/VIMC-2383
=> i2383: Allow missing archive directory

appveyor.yml
Caught in the crossfire with remotes changing behaviour
https://github.com/krlmlr/r-appveyor/issues/57
https://github.com/krlmlr/r-appveyor/issues/127
https://github.com/r-lib/remotes/issues/202
=> i2420: Fix appveyor

DESCRIPTION, NEWS.md, R/migrate.R, R/paths.R, R/util.R, man/orderly_migrate.Rd, tests/testthat/test-migrate.R, tests/testthat/test-util.R
Addresses issues seen on @cmukandavire's computer today when archive migrations fail
=> i2449: Improvements to archive migration

R/recipe_read.R, inst/examples/nodata/orderly_config.yml, inst/examples/nodata/src/example/orderly.yml, inst/examples/nodata/src/example/script.R, tests/testthat/test-recipe-read.R
This feels like there needs to be more tests, but I'm not sure what.
=> Make data key optional

inst/examples/demo/demo.yml, inst/examples/demo/src/spaces/orderly.yml, inst/examples/demo/src/spaces/script.R
check here for the build - http://teamcity.montagu.dide.ic.ac.uk:8111/viewType.html?buildTypeId=montagu_Orderly_BuildContainer
=> i2761: Add demo case with spaces

.Rbuildignore, DESCRIPTION, NEWS.md, R/cleanup.R, R/logging.R, R/recipe_commit.R, R/recipe_run.R, R/remote.R, README.md, man/orderly_cleanup.Rd, man/orderly_commit.Rd, man/orderly_log.Rd, man/orderly_run.Rd, man/orderly_run_remote.Rd, man/orderly_test_start.Rd, vignettes/orderly.Rmd, vignettes/src/orderly.R
This PR is primarily concerned with the README as the main landing point for the package.  There will be more documentation work to get the vignettes updated too.
I've put down more than the usual number of people for review because writing is hard. Please propose alternative ways of phrasing what is here, or an entirely new way of hooking people in.
=> VIMC-2883: first pass at documentation overhaul

.travis.yml, DESCRIPTION, R/vault.R, appveyor.yml
@r-ash added this to `vaultr` once we started using the same pattern for dettl
=> VIMC-2922: move secret resolution into vaultr

.travis.yml
Minor update to the travis configuration to add testing against both release and devel
=> VIMC-3179: Test on devel and release

DESCRIPTION, tests/testthat/helper-orderly.R, tests/testthat/test-changelog.R, tests/testthat/test-cleanup.R, tests/testthat/test-db.R, tests/testthat/test-file-store.R, tests/testthat/test-global.R, tests/testthat/test-main.R, tests/testthat/test-orderly.R, tests/testthat/test-query.R, tests/testthat/test-readme.R, tests/testthat/test-recipe-read.R, tests/testthat/test-remote-path.R, tests/testthat/test-run.R, tests/testthat/test-slack.R, tests/testthat/test-testing.R, tests/testthat/test-util.R, tests/testthat/test-z-demo.R
A long and sad story.
Because I submitted the package to CRAN directly, this PR should be rebased against current master (not merged) so that the tag ends up at the final commit
=> VIMC-3341: updates to get package back on CRAN

DESCRIPTION, NEWS.md, R/config.R, R/db.R, R/recipe_run.R, R/recipe_test.R, R/util.R, man/orderly_cleanup.Rd, man/orderly_db.Rd, man/orderly_deduplicate.Rd, man/orderly_example.Rd, man/orderly_latest.Rd, man/orderly_migrate.Rd, man/orderly_new.Rd, man/orderly_pull_dependencies.Rd, man/orderly_rebuild.Rd, man/orderly_run.Rd, man/orderly_run_remote.Rd, man/orderly_test_start.Rd, tests/testthat/test-config.R, tests/testthat/test-db.R, tests/testthat/test-run.R, vignettes/orderly.Rmd
This PR aims to address the database instance problem discussed in more detail in the corresponding ticket https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-3302
=> vimc-3302: more flexible database selection

DESCRIPTION, R/slack.R, tests/testthat/test-slack.R
Only one of these is tested, the other is tested empirically at least.  That whole server management section of the config needs a big overhaul at some point...
=> VIMC-3686: Fix two bugs introduced in configuration refactor

docker/build_website
I think that this will fix the check on git push of the website. Probably will take one or two goes to get right though...
=> Fix bash drama

README.md
The link will only work when we've merged the README changes in orderly.rstudio in
=> Add note about addins to README

.github/workflows/R-CMD-check.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, R/db2.R, R/recipe_commit.R, R/util.R, docker/Dockerfile, man/orderly_commit.Rd, tests/testthat/test-db.R, tests/testthat/test-util.R
We should merge this once https://github.com/r-dbi/RSQLite/pull/345 has been merged into master
=> Replace report commit retries with SQLite busy handler

DESCRIPTION, NEWS.md, R/orderly_recipe_depends.R, tests/testthat/test-query-search.R
This PR fixes another unactionable error message by indicating which query has failed
=> VIMC-4742: Clearer error message on query failure

.Rbuildignore, DESCRIPTION, _pkgdown.yml
As suggested by @maelle 
@maelle: if there's anything else we should be doing, feel free to comment here :)
=> Add pkgdown index to curate refs

DESCRIPTION, R/orderly_recipe_artefacts.R, tests/testthat/test-orderly-recipe.R
Reported by @RaphaelS1
Current message is possibly still unclear but at least it throws correctly
=> Handle zero-length artefact names during validation

DESCRIPTION, R/testing.R
Needed for https://github.com/vimc/orderly.server/pull/72
=> Use absolute path for testing git remote

DESCRIPTION, R/query_search.R, tests/testthat/test-query-search.R
=> Better handling of empty queries

.github/workflows/pkgdown.yaml, DESCRIPTION, _pkgdown.yml, tests/testthat/test-slack.R
Minor bit of maintenance here, just updating actions so that the pkgdown site actually builds. There's another test that needs skipping that I really thought I had skipped previously
=> Update pkgdown action
