vimc/orderly1

- .travis.yml
- DESCRIPTION
- R/config.R
- R/db.R
- R/remote.R
- R/remote_api.R
- R/util.R
- R/vault.R
- man/default_remote.Rd
- man/orderly_publish_remote.Rd
- man/orderly_run_remote.Rd
- tests/testthat/test-config.R
- tests/testthat/test-remote.R
- tests/testthat/test-util.R
This work needs https://github.com/vimc/montagu-r/pull/5
This is primarily to support the ebola response and extends the orderly remote functions a bit to support non-VIMC servers.  It's going to need a further round of rationalisation once we really disentangle montagu and orderly.
The `orderly_config.yml` picks up additional options
- `vault_server` - the address of the vault that we should use
- `api_server` - a set of remote api servers
Most of the logic is within the validation function in config.R and also in `orderly_remote_api_server`
> I1772 - support basic auth and non-montagu servers

- R/remote.R
- tests/testthat/test-remote.R
This one is at least much smaller, probably do before #14 
Turns out that passing `remote = <whatever>` really didn't work properly.  This tries to resolve things properly, so there's quite a bit more logic in `get_remote()`, with accompanying tests
> i1794: Fix specification of remotes

- R/init.R
- R/main.R
- R/new.R
- R/recipe_commit.R
- R/recipe_run.R
- R/remote_api.R
- R/remote_path.R
- R/runner.R
- R/testing.R
- R/util.R
- tests/testthat/test-util.R
The deluge continues...
DYK that if `file.copy` fails it doesn't tell you or error?  And that it does not overwrite by default?  Neither of these are useful for our needs here.  This PR fixes that
> i1814: better workaround for file.copy

- R/recipe_read.R
- R/recipe_run.R
- R/util.R
- inst/examples/depends/src/depend2/orderly.yml
- inst/examples/depends/src/depend2/script.R
- tests/testthat/test-run.R
I thought this was possible but it turns out not to be, as found by @tinigarske 
The format here follows that if the artefacts.  It's not very beautiful because it means you have to use the ordered map syntax but I think that's unavoidable.  So we have
```yaml
depends:
- example:
id: latest
draft: true
use:
previous1.rds: data.rds
- example:
id: latest
draft: false
use:
previous2.rds: data.rds
```
In the case where only one copy of `example` is used one may specify:
```yaml
depends:
example:
id: latest
draft: true
use:
previous1.rds: data.rds
```
(but including the dash before `example` would also be OK)
An alternative would have been to have done:
```yaml
depends:
example:
- id: latest
draft: true
use:
previous1.rds: data.rds
- id: latest
draft: false
use:
previous2.rds: data.rds
```
but …
> i1875: allow multiple versions of a report to be used at once

- R/slack.R
- tests/testthat/test-slack.R
This should fix the problem where the slack message didn't include the link to the report.
It still might be temperamental about whether or not it includes time elapsed information, this seems related to `config$api_server$<SERVER_ID>$server$server$name` not being set I think.
> Add name variable to fix link in slack message

- .travis.yml
- DESCRIPTION
- NEWS.md
- R/vault.R
- appveyor.yml
- tests/testthat/helper-orderly.R
- tests/testthat/test-aaa.R
- tests/testthat/test-util.R
- tests/testthat/test-zzz.R
There are breaking changes in the next version of vaultr - this updates the package to use them.  There are a group of these PRs and they should be merged together, followed by updating the drat in order to minimise disruption.
> i2445: upgrade vaultr

- DESCRIPTION
- NEWS.md
- R/config.R
- R/slack.R
- R/util.R
- tests/testthat/test-slack.R
- tests/testthat/test-util.R
Two errors in here:
* we throw on catching an error (:upside_down_face:)
* we never resolved the SLACK_URL env var (or any other used in the remote configuration outside of the args)
> i2553: fix orderly slack handling

- DESCRIPTION
- NEWS.md
- R/config.R
- R/runner.R
- man/orderly_runner.Rd
- tests/testthat/test-config.R
- tests/testthat/test-z-runner.R
This honours a configuration already present in montagu-reports, but currently ignored by orderly
> i2642: Prevent git reference switching on production

- DESCRIPTION
- NEWS.md
- R/db2.R
- R/slack.R
- R/zzz.R
- inst/database/schema.yml
- tests/testthat/test-db.R
- tests/testthat/test-git.R
- tests/testthat/test-slack.R
This creates new columns in the db schema and populates them with git information that we already have (so no data migrations are needed).
Because I was poking about with the git structure I've fixed the failure we were seeing where reports on science with the runner do not have version information printed in the slack message
> i2615: add git information to the schema

- DESCRIPTION
- NEWS.md
- R/remote.R
- man/orderly_run_remote.Rd
This PR does very little towards the ticket, just updating a few arguments as they're passed through to the runner.
We have a new `wait` parameter: that's the _client-side_ timeout as opposed to `timeout` which is for the server.  The PR in `montagu-r` will forward that appropriately
See https://github.com/vimc/montagu-r/pull/20 and https://github.com/vimc/orderly.server/pull/10
> i2517: Better behaviour with report timeout

- DESCRIPTION
- NEWS.md
- R/cleanup.R
- R/db.R
- R/db2.R
- R/publish.R
- R/recipe_commit.R
- scripts/schema/create_schema
- tests/testthat/helper-orderly.R
- tests/testthat/test-db.R
- tests/testthat/test-publish.R
- tests/testthat/test-run.R
- tests/testthat/test-util.R
Remove the old db schema
Most of the diff here is:
* removing code that used to maintain the old `orderly` table in the db
* renaming lots of functions from `_db2_` to `_db_`
* fixing up tests that checked on the state of the db (I have kept the intent of the tests the same)
There are two opportunistic fixes of other tests, flagged below.
Before merging this we should double check that this works with the reporting api; the `orderly.server` and the `montagu-orderly` containers have been updated now on the `i2769` branch so can be used in integration tests
> i2769: remove old db schema

- DESCRIPTION
- NEWS.md
Sorry, this should have been part of the previous PR (#94) - all user-visible changes really must have a version increment.  I'd done this locally but forgotten to push
> VIMC-2919: Bump version and add NEWS

- DESCRIPTION
- NEWS.md
- R/db.R
- R/paths.R
- R/runner.R
- R/util.R
- man/orderly_runner.Rd
- tests/testthat/test-db.R
- tests/testthat/test-util.R
- tests/testthat/test-z-runner.R
This PR will add a periodic backup to be run from the runner.
The use case/issue is that if we are backing up the system with rsync we have the potential to back up an inconsistent db, which is a problem with data now being stored on the OrderlyWeb side as well as the rebuildable orderly db.
With the changes here the db is backed up every 10 minutes by default.  To make the backup process safe to inconsistencies, we first backup the backup by moving it to `<name>.prev` (which is atomic) then doing the new backup
> VIMC-2882: back up database periodically

- DESCRIPTION
- NEWS.md
- R/config.R
- R/db2.R
- R/new.R
- R/recipe_read.R
- R/util.R
- inst/database/schema.yml
- tests/testthat/test-db.R
This PR makes it easier for external applications (i.e., OrderlyWeb) to interact with custom fields by putting them elsewhere than the main table (VIMC-2929 will remove them from the main table).
Two new tables are created:
* `custom_fields`, which holds the field definitions
* `report_version_custom_fields`, which holds the fields associated with each version
The fields are all constrained to be `TEXT` so this part of validation comes out of the config.
Once OrderlyWeb supports this new format, the old approach can be removed - this can be done in a separate PR (and for ease of deploy probably should be) - the ticket is VIMC-2929 and I've got a branch for this ([content](https://github.com/vimc/orderly/tree/vimc-2929), [compare](https://github.com/vimc/orderly/compare/vimc-2768...vimc-292 …
> VIMC-2768: Move custom fields into a separate table

- DESCRIPTION
- R/changelog.R
- R/db2.R
- R/paths.R
- R/recipe_run.R
- R/testing.R
- inst/database/schema.yml
- inst/migrate/0.6.7.R
- tests/testthat/test-changelog.R
- tests/testthat/test-migrate.R
- tests/testthat/test-run.R
- tests/testthat/test-z-demo.R
- vignettes/changelog.Rmd
This is needed for orderly web because we need something that will persist across DB rebuilds.
Before merging we should check to see the impact on the reporting portal and orderly web
> VIMC-2696: Global PK for changelog entries

- DESCRIPTION
- NEWS.md
- R/config.R
- inst/examples/changelog/orderly_config.yml
- inst/examples/db1/orderly_config.yml
- inst/examples/db2/orderly_config.yml
- inst/examples/demo/orderly_config.yml
- inst/examples/depends/orderly_config.yml
- inst/examples/example/orderly_config.yml
- inst/examples/interactive/orderly_config.yml
- inst/examples/minimal/orderly_config.yml
- inst/examples/nodb/orderly_config.yml
- inst/examples/other/orderly_config.yml
- inst/examples/resources/orderly_config.yml
- inst/orderly_config_example.yml
- scripts/schema/orderly_config.yml
- tests/testthat/example/orderly_config.yml
- tests/testthat/example_config.yml
- tests/testthat/test-config.R
- tests/testthat/test-db.R
- tests/testthat/test-envir.R
- tests/testthat/test-migrate.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-z-runner.R
- vignettes/src/orderly.R
This PR will harmonise the database configuration with dettl and with the api server configuration by moving the arguments into an explicit block, so that:
```
db:
driver: pkg::fn
arg1: value
arg2: value
```
becomes
```
db:
driver: pkg::fn
args:
arg1: value
arg2: value
```
This is handled in the same way as the work on database/source, where using the old style is supported for a while, with a warning.
Moving to this layout will allow us to support orderly-level options alongside the drivers in the future (e.g., `cache: false` for preventing caching of database into the `data` directory).
(almost all the lines in the diff here are updating the configurations; there are only a handful of lines of code changed)
> VIMC-1986: improve the db configuration

- R/recipe_read.R
- R/recipe_run.R
- R/util.R
- tests/testthat/test-global.R
- tests/testthat/test-readme.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-run.R
This PR moves the file hash calculation quite early in the process; it's not at recipe read but I think that's ok because it requires some calculation with directories etc and feels most naturally done when we prepare the new working directory.
This expands the previous "no files changed during run" to cover _all_ files that orderly looks after (somewhat different treatment was required for the dependencies).  The logic with README.md files and how directory listings are computed has been tidied, and I found some undocumented behaviour with globals that I've annotated with  new and existing issues.
> VIMC-2942: Compute all file hashes before run

- docker/Dockerfile
This PR will update the version of R used from 3.5.0 to 3.5.3
At the same time, it will unpin the MRAN "snapshot" repository that is used, instead using CRAN.  This will stop some annoying issues with not being able to install packages that were not on CRAN when this version of R was released
> VIMC-2969: Update R in the orderly container, unpinning MRAN

- R/testing.R
- README.md
- tests/testthat/test-db.R
- tests/testthat/test-git.R
- tests/testthat/test-main.R
- tests/testthat/test-query.R
- tests/testthat/test-run.R
- tests/testthat/test-tools.R
- tests/testthat/test-util.R
- tests/testthat/test-z-demo.R
- tests/testthat/test-z-runner.R
This PR will avoid a bunch of tests on CRAN - mostly ones involving git, but also the runner.  These are unlikely to work across all possible platforms, and depend on external software (notably a version of git that deals well with hidden files)
> VIMC-2967: avoid platform dependent things in tests

- DESCRIPTION
- NEWS.md
- R/slack.R
- tests/testthat/test-slack.R
This PR will fix a bug that crept in during the metadata rework.
The data used in constructing the slack message changed slightly and this broke the slack notification.  That leads to confusing error messages after a successful report run using orderly web.
Code changes here are minimal, the tests are updated and then a new integration test has been added to prevent future regressions
> VIMC-2992: Fix slack payload

- DESCRIPTION
- NEWS.md
- R/db.R
- R/db2.R
- R/migrate.R
- R/recipe_commit.R
- R/recipe_run.R
- R/remote.R
- man/orderly_pull_dependencies.Rd
- tests/testthat/test-migrate.R
- tests/testthat/test-orderly.R
- tests/testthat/test-remote-path.R
- tests/testthat/test-remote.R
This PR will add reports into the DB as they are pulled, which is required for commiting any reports that that have imported dependencies.  To make that work we now also recursively download reports
> VIMC-2855: add pulled reports into DB

- DESCRIPTION
- R/db2.R
- tests/testthat/test-changelog.R
This PR will improve the error message when changelog labels have changed, requiring a db rebuild by making it clearer that one must run the function
As reported by @Imai-N
> VIMC-3057: Better error message when changelog labels have changed

- DESCRIPTION
- R/recipe_read.R
- tests/testthat/test-recipe-read.R
If a report has a resource directory specified by
```
resources:
- data/
```
The report will run correctly with all the contents of data copied correctly.
The files in data will be listed as unexpected artefacts since orderly the files are copied to
```
data/filename.csv
```
but orderly expects the file to be
```
data//filename.csv
```
[This might also cause problems running this report on a windows OS]
This fix removes a trailing slash - we could probably go further sanitizing filenames (and other entries) in the yaml
> strip out trailing slashes from resource directories

- DESCRIPTION
- NEWS.md
- R/recipe_run.R
- inst/migrate/0.7.12.R
- tests/testthat/test-migrate.R
- tests/testthat/test-run.R
This PR checks reports for a sink imbalance.  This is particularly important where sinks are used to create artefacts, as seen in VIMC-3128 as this modifies the artefact after creation.
The approach is directly modelled after the device imbalance check
> VIMC-3129: Check for sink imbalance

- inst/examples/demo/src/html/myreport.Rmd
- inst/examples/demo/src/html/script.R
- inst/examples/knitr/src/example/report.Rmd
- inst/examples/knitr/src/example/script.R
- tests/testthat/test-run.R
While `rmarkdown::render` is certainly a nicer way of doing this, it induces an error in the pandoc system package for tests, which will be a problem on CRAN (I believe it does not exist on Solaris, for example).
This PR uses plain knitr for the translation
> VIMC-3137: Remove uses of pandoc

- R/testing.R
- tests/testthat/test-util.R
This PR uses a slightly different hack for the windows file unhiding:
* we only execute `attrib` on windows
* tests use mocks to check that this would not be run on unix and would be run on windows
> VIMC-3140: alternative approach to the windows unhiding

- DESCRIPTION
- R/testing.R
- R/util.R
- docker/Dockerfile
- tests/testthat/helper-orderly.R
- tests/testthat/test-util.R
This PR will remove `utils::zip` which has proven to be not that reliable, in favour of the `zip` package.  There should be no user-facing changes as a result of this, except that things will be slightly better behaved on windows.
It's possible that this removes the need for the previous rounds of hacking (VIMC-3140 / #127, VIMC-3133 / #125) and perhaps in light of that the net change there could be removed.
> VIMC-2968: swap utils::zip for the zip package

- DESCRIPTION
- NEWS.md
- R/main.R
- R/runner.R
- R/util.R
- docker/Dockerfile
- inst/script
- tests/testthat/test-main.R
- tests/testthat/test-slack.R
- tests/testthat/test-z-runner.R
This PR will overhaul the cli interface to use docopt rather than optparse. The parameter interface is changed now so that we pass in parameters as simple key-value pairs rather than json, as json was _awful_ to use on a cli.  So now we might write:
```
orderly run other nmin=0.5
```
The actual type inference of parameters might cause some problems but we'll deal with that later...
This slightly affects the orderly.server but not that much because running with parameters is not enabled.  I am going to address this in VIMC-3144 on that package
> VIMC-2469: refactor the cli interface

- DESCRIPTION
- NEWS.md
- R/db2.R
- R/recipe_read.R
- R/recipe_run.R
- inst/database/schema.yml
- inst/examples/demo/src/global/orderly.yml
- inst/examples/global/src/example/orderly.yml
- inst/migrate/0.7.15.R
- tests/testthat/test-global.R
- tests/testthat/test-migrate.R
- tests/testthat/test-recipe-read.R
- vignettes/orderly.Rmd
This PR will allow global resources to be organised into subdirectories.  Previously this was not really possible as it was ambiguous what
```
global_resources:
- path/file.csv
```
should do - should it copy to the current report as `path/file.csv` or as `file.csv` (this ambiguity does not exist for ordinary resources as this is just a declaration that they exist).
To solve this we take the same approach as dependencies where files can be renamed:
```
global_resources:
file.csv: path/file.csv
```
The lhs is the destination - that is the order used in the dependencies.  This approach allows arbitrary renaming, which is quite nice.
There are changes to the schema as a result of this - a new table exists to map the original names.
I do not believe that any report currently uses global …
> VIMC-2961: Allow resources in subdirectories (and with different names)

- DESCRIPTION
- NEWS.md
- R/main.R
- R/migrate.R
- man/orderly_migrate.Rd
- tests/testthat/test-main.R
- tests/testthat/test-migrate.R
This PR will add an option to `orderly_migrate` (and the cli) to clean up old migration backup files (like `orderly_run_0.6.0.rds`). These clutter up the downloaded zips and should be safe to delete eventually
> VIMC-3157: support cleaning up old migration files

- tests/testthat/helper-orderly.R
- tests/testthat/test-util.R
We skip_if_no_git() twice - both in test-util.R (in this PR, lines 147, 177).
In both cases, we want to skip on cran - hence I've moved the existing
skip_on_cran() from one of those functions into the top of skip_if_no_git()
(in helper-orderly.R), and now it covers both cases.
> Skip git tests in test-util (163,165,167)

- .Rbuildignore
- .gitignore
- R/util.R
- tests/testthat/test-util.R
This PR reduces the number of orderly-related environment variables that will be recorded alongside the metadata. Previously we'd grabbed everything starting with `ORDERLY_` but that's a bit much if there are any orderly web related secrets.
I've checked and we're ok on science/uat with this, but it seems worth excluding the most obviously bad cases here for now
> VIMC-3130: Exclude potentially sensitive environment variables

- DESCRIPTION
- NEWS.md
- R/recipe_read.R
- R/recipe_run.R
- inst/examples/demo/src/other/orderly.yml
- inst/examples/example/src/example/orderly.yml
- inst/examples/interactive/src/count_param/orderly.yml
- inst/examples/other/src/other/orderly.yml
- inst/examples/parameters/src/example/orderly.yml
- inst/orderly_example.yml
- tests/testthat/example_report.yml
- tests/testthat/test-orderly.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-run.R
- vignettes/orderly.Rmd
This PR allows `orderly.yml` to specify parameter values.  This was requested a long time ago in #8
With the new deprecated functionality approach we've used for similar changes this is fairly straightforward to implement, and it will be less painful to do this change before the initial release.
> VIMC-2413: Allow default parameter values

- DESCRIPTION
- R/config.R
- R/remote.R
- R/remote_path.R
- R/slack.R
- tests/testthat/test-config.R
- tests/testthat/test-remote-path.R
- tests/testthat/test-slack.R
This PR removes the last bit of montagu-specific details (I hope!) from orderly by using the `report_url` method of orderly remotes.
As implemented in orderlyweb via https://github.com/vimc/orderlyweb/pull/5 (VIMC-3168) and in the `orderly_remote_file` remote included in orderly.
Update to montagu-reports is here: https://github.com/vimc/montagu-reports/pull/345
> VIMC-3105: use remote to compute url for slack 

- vignettes/orderly.Rmd
This PR will expand the section on using vault for secret management
I had thought that there was more to add here, but secret resolution
is only supported for the db args and for the slack url.
> VIMC-3159: Minor updates to the vault configuration section

- DESCRIPTION
- NEWS.md
- R/recipe_test.R
- tests/testthat/test-run.R
This PR is in response to a CRAN request:
> Dear package maintainer,
> 
> your package orderly_1.0.1.tar.gz did *not* pass 'R CMD check' on
> Windows and will be omitted from the corresponding CRAN directory.
> Please check the attached log-file and submit a version
> with increased version number that passes R CMD check on Windows.
>
> R version 3.6.1 (2019-07-05)
```
* checking for unstated dependencies in 'tests' ... OK
* checking tests ... [173s] ERROR
Running 'testthat.R' [172s]
Running the tests in 'tests/testthat.R' failed.
Complete output:
> library(testthat)
> library(orderly)
> 
> test_check("orderly")
-- 1. Failure: orderly_test_check requires test mode (@test-run.R#353)  --------
`orderly_test_check()` threw an error with unexpected message.
Expected match: "Not running in …
```
> VIMC-3205: Don't check case in orderly_test_check

- .dockerignore
- R/runner.R
- README.md
- README.md.in
- docker/Dockerfile
- docker/Dockerfile.nogit
- tests/testthat/helper-orderly.R
- tests/testthat/test-util.R
- tests/testthat/test-z-runner.R
This PR will fix the test failures seen on Solaris:
https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/orderly-00check.html
There are two here:
* The runner does not correctly start when git is not found, and I've updated the initialisation to deal with that more gracefully
* The canonical casing test does not work, and that is uninteresting (all unix-like systems we assume to be case sensitive) so I've skipped the relevant tests (`canonical case: single file`, `canonical case: relative path`, `canonical case: absolute path`)
> VIMC-3208: work around solaris test failures

- NEWS.md
- R/recipe_run.R
- tests/testthat/test-run.R
`orderly::orderly_run` now strips a leading `src/` if provided, allowing easier tab-completion of report names (VIMC-3226).
> vimc-3226: Strip leading src/ when running reports

- docker/Dockerfile
This is required in order to support the `Hmisc` package which has a dependency `latticeExtra` which depends on R >= 3.6.0 - I think this should be quite safe to upgrade by now
> vimc-3373: Update R version

- DESCRIPTION
- NEWS.md
- R/recipe_run.R
- R/util.R
- tests/testthat/test-orderly.R
- tests/testthat/test-util.R
As discussed with the coronavirus group, this would allow some (somewhat) automated workflows for reproducing stochastic analyses, even if `set.seed` is not used.
If we store `.Random.seed` then we can in theory restore the state of the RNG:
```r
> set.seed(1)
> rs <- .Random.seed
> runif(10)
[1] 0.26550866 0.37212390 0.57285336 0.90820779 0.20168193 0.89838968
[7] 0.94467527 0.66079779 0.62911404 0.06178627
> .Random.seed <- rs
> runif(10)
[1] 0.26550866 0.37212390 0.57285336 0.90820779 0.20168193 0.89838968
[7] 0.94467527 0.66079779 0.62911404 0.06178627
```
There's no support for automatically using this on rerun (and reports where this is important should use the `set.seed()` functionality, which is preferred) but we can look at restoring it when doing VIMC-3378
> vimc-3375: Save random seed alongside metadata

- DESCRIPTION
- NEWS.md
- R/config.R
- R/query.R
- R/recipe_read.R
- R/recipe_run.R
- R/recipe_test.R
- inst/init/orderly.yml
- man/orderly_run.Rd
- man/orderly_test_start.Rd
- tests/testthat/examples/depends/src/depend/orderly.yml
- tests/testthat/examples/depends/src/depend2/orderly.yml
- tests/testthat/helper-orderly.R
- tests/testthat/test-orderly.R
- tests/testthat/test-query.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-remote-path.R
- tests/testthat/test-run.R
- vignettes/orderly.Rmd
This PR is intended to (eventually) replace the `draft: true` trick from orderly.yml's depends, by the ability to change where dependencies come from when running the report. This means that the underlying source does not need updating and we get fewer cases of reports being merged with draft: true sticking around
> vimc-3377: more flexible draft selection

- .travis.yml
- DESCRIPTION
- NEWS.md
- R/config.R
- R/vault.R
- appveyor.yml
- tests/testthat/test-config.R
- tests/testthat/test-util.R
- vignettes/orderly.Rmd
Now allows all connection options to be set in the orderly configuration, not just the vault address.  This will make the eventual vimc -> mrc-ide vault a lot easier because we can use a different github mount for the authentication.  
Requires https://github.com/vimc/vaultr/pull/26 to be merged and references to vimc-3397 to be removed from the .travis.yml and appveyor.yml
> VIMC-3372: Expanded vault configuration

- DESCRIPTION
- NEWS.md
- R/recipe_run.R
- man/orderly_run.Rd
- man/orderly_test_start.Rd
- tests/testthat/test-db.R
- tests/testthat/test-run.R
This PR fixes a problem that @sangeetabhatia03 and @imai-n found - if the user provides invalid parameters (from the point of view of orderly's data model) then the error is only thrown when the report is commited, and then with an incomprehensible message.  Here, we validate the parameters before running, and provide better messages that can be actioned
> VIMC-3411: Validate parameters early

- DESCRIPTION
- NEWS.md
- R/config.R
- R/vault.R
- tests/testthat/test-config.R
All $vault and $vault_server are now [['vault']] and [['vault_server']].
One added test - which is somewhat water under the bridge - but will fail if the above change on config.R:55 is rolled back.
> Vimc 3424 - possible autocompletion of vault to vault_server

- DESCRIPTION
- NEWS.md
- R/config.R
- R/db.R
- R/remote.R
- R/slack.R
- R/util.R
- R/vault.R
- tests/testthat/test-config.R
- tests/testthat/test-envir.R
- tests/testthat/test-util.R
This solves a problem where (say) a remote is configured like:
```
remote:
main:
driver: orderlyweb::orderlyweb_remote
args:
host: orderly.example.com
port: 443
token: $VAULT_AUTH_GITHUB_TOKEN
```
and the environment variable is not set.  At present the user just gets an error saying
```
> orderly_pull_dependencies("explore_delays", remote = "testing")
Error: 'token' must be a scalar
> traceback()
15: stop(sprintf("'%s' must be a scalar", name), call. = FALSE)
14: assert_scalar(x, name)
13: assert_scalar_character(token)
12: orderlyweb_token_constant(token)
11: .subset2(public_bind_env, "initialize")(...)
10: R6_orderlyweb_api_client$new(host, port, token, name = name, 
https = https, prefix = prefix, api_version = api_version, 
insecure = insecure, verbose = verbose)
9: …
```
> vimc-3386: more informative resolution of environment variables

- DESCRIPTION
- NEWS.md
- R/db.R
- R/main.R
- R/recipe_run.R
- tests/testthat/test-db.R
- tests/testthat/test-main.R
- tests/testthat/test-run.R
This PR adds an `--instance` switch to the cli. So far so easy.
If we make it easy to change the instance we need to record what was used!  So this makes a quick stab at recording the used instance into the orderly_run.rds.  This does not affect many reports (as in, instances are only a thing since recently) but it would be nice to get this in asap so that we can easily work out what came from where. Later we might lock down instance on production too
> vimc-3460: add orderly instance to cli runner and to the run rds

- DESCRIPTION
- NEWS.md
- R/main.R
- tests/testthat/test-main.R
This adds a `pull` sub command that allows pulling a report or a dependency.  This might come in useful if we use that larger cluster node for running some reports.
> vimc-3466: expose the dependency pull on the CLI

- DESCRIPTION
- NEWS.md
- R/cleanup.R
- R/query.R
- man/orderly_list_drafts.Rd
- tests/testthat/test-cleanup.R
- tests/testthat/test-query.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-z-runner.R
This PR fixes a fairly subtle bug found by @sangeetabhatia03 in the ncov project.
When dependencies are allowed to be drafts (e.g., with `use_draft = TRUE`, `use_draft = "newer"` or with `draft: true` in the orderly.yml), then there is a chance that we will pull in a failed version.  This PR modifies the query functions to skip over these most of the time.  Failed reports are detected by the presence of `orderly_run.rds`
> mrc-3467: don't count failed drafts when using dependencies

- DESCRIPTION
- NEWS.md
- R/recipe_read.R
- tests/testthat/test-recipe-read.R
As reported by @jeffeaton in VIMC-3503/#174, this PR adds a more human friendly check.  If artefacts are provided like:
```
artefacts:
- survey_individuals.csv
```
the error message now says:
```
Error: Your artefacts are misformatted.  You must provide a 'type'
and a description for each, and each logical artefact may
contain multiple files.  For example, you might use
artefacts:
- data:
description: These are data for x, y, z
filenames:
- survey_individuals.csv
other alternatives to 'data' are 'staticgraph', 'interactivegraph', 'report', 'interactivehtml'
```
It *always* proposes `data` as an artefact type, as everything is kind of data.
Fixes #168
> VIMC-3511: Better error messages when artefacts are provided as string array

- DESCRIPTION
- NEWS.md
- R/config.R
- R/db2.R
- R/recipe_read.R
- R/recipe_run.R
- inst/database/schema.yml
- inst/examples/demo/orderly_config.yml
- inst/examples/demo/src/interactive/orderly.yml
- inst/examples/demo/src/other/orderly.yml
- man/orderly_run.Rd
- tests/testthat/test-config.R
- tests/testthat/test-db.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-run.R
- tests/testthat/test-z-demo.R
This PR adds very basic support for tags.  At the moment, the main thing it implements is the db structure (new tables `tag` and `report_version_tag`).  Nothing useful can be done with tags within orderly.  The demo data set has tags added to two reports for use in orderlyweb testing.
> VIMC-3514: Basic support for tags

- .travis.yml
- DESCRIPTION
- NEWS.md
- R/develop.R
- R/recipe_run.R
- R/util.R
- man/orderly_develop_start.Rd
- man/orderly_run.Rd
- tests/testthat/test-develop.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-run.R
- vignettes/orderly.Rmd
This PR loads the environment variables in orderly_envir.yml and makes them available as ordinary environment variables (`Sys.getenv()`) during a report build. As requested by @jeffeaton in #180 
Better handling of secrets will be done in a subsequent PR as that's a bit more tricky, but see vimc-3536 as I have a good idea for this
> vimc-3530: Use orderly_envir.yml environment variables during report run

- DESCRIPTION
- R/logging.R
- R/util.R
- tests/testthat/helper-orderly.R
- tests/testthat/test-develop.R
- tests/testthat/test-log.R
- tests/testthat/test-migrate.R
- tests/testthat/test-remote-path.R
- tests/testthat/test-remote.R
- tests/testthat/test-testing.R
- tests/testthat/test-util.R
This PR adds nicer log printing, by using the crayon package (now that we depend on it).
Just simple at the moment, but I've highlighted cases where the log topic is "warning" and "unexpected" (plus the failure modes in migrations) - we can add more to the list as it seems useful but a little restraint goes a long way...
> vimc-3515: nicer log printing

- DESCRIPTION
- R/remote.R
- R/slack.R
- tests/testthat/test-remote.R
This is a stopgap fix, really; it allows SLACK_URL to be missing (required on user machines). The other half is fixed via https://github.com/vimc/montagu-orderly-web/pull/11 which solves the problems that we saw together
> vimc-3543: Try and fix environment variable resolution with remotes

- DESCRIPTION
- NEWS.md
- R/main.R
- tests/testthat/test-main.R
Catch the error when parsing - we're only doing this to detect numbers properly.  If we are passed in a quoted string (e.g., to escape this conversion, or with spaces), then remove the quotes too
> vimc-3550: better command line parsing

- DESCRIPTION
- NEWS.md
- R/recipe_read.R
- R/recipe_run.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-run.R
- vignettes/orderly.Rmd
This PR builds on #181 in spirit, though with a different approach.
We allow a `secrets:` section in orderly.yml, in which the user includes values that should be recovered from the vault.  These come through as R variables, named in the yaml map.
> vimc-3536: access to secrets from an orderly report

- .travis.yml
- DESCRIPTION
- R/config.R
- tests/testthat/test-config.R
If a new version of orderly introduces new fields, we should be able to throw the "version requirement" error rather than the unknown fields error.  This PR reorders the configuration checking, and adds a test.  There should be no user-visible effect for already-working configurations
> VIMC-3442: Check orderly version requirements before the fields

- DESCRIPTION
- NEWS.md
- R/recipe_read.R
- R/recipe_run.R
- R/util.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-run.R
- tests/testthat/test-util.R
- vignettes/orderly.Rmd
This PR will
* Allow user to specify named environment variables in their `orderly.yml`
* Which are then made available to report script via the specified name
One note - I changed the default `Sys_getenv` to check for empty vars too. This will change previous behaviour but it did not fail any tests and looks like a sensible default to me? Happy to be told otherwise and can rethink how that check is working.
> VIMC-3558: Users can access environment variables specified in orderly.yml

- DESCRIPTION
- NEWS.md
- R/config.R
- tests/testthat/test-config.R
This fixes a problem seen on science with the default instance just not working
> VIMC-3589: Fix database instance selection with defaults

- R/changelog.R
- R/config.R
- R/recipe_read.R
- R/remote_path.R
- R/runner.R
- R/slack.R
- tests/testthat/helper-orderly.R
- tests/testthat/test-config.R
- tests/testthat/test-db.R
- tests/testthat/test-deduplicate.R
- tests/testthat/test-develop.R
- tests/testthat/test-envir.R
- tests/testthat/test-helpers.R
- tests/testthat/test-main.R
- tests/testthat/test-migrate.R
- tests/testthat/test-recipe-read.R
- tests/testthat/test-remote-path.R
- tests/testthat/test-remote.R
- tests/testthat/test-run.R
- tests/testthat/test-slack.R
- tests/testthat/test-util.R
- tests/testthat/test-z-runner.R
This is a minimal refactor of the orderly configuration that aims to add no functionality, but to make things more maintainable. This is very much going to be a work in progress, and there are quite a few things that would be better as methods on the object (particularly with respect to the database)
> vimc-3593: refactor orderly's configuration

- DESCRIPTION
- NEWS.md
- R/util.R
This PR fixes (empirically) a bug where the directory case check caused downloading and copying of an archive from a remote to fail, on windows paths where a name with spaces was converted into a "short name".
VIMC-3594 contains the real problem, which will take more rooting out. This is probably unreplicable without a windows system and a username with spaces in it, so some carful mocking will be required when fixing VIMC-3594
> VIMC-3595: Fix error downloading reports

- docker/Dockerfile
- docker/Rprofile.site
This PR attempts to fix the docker build by writing the entire Rprofile.site to a reasonable value, setting the mirror to CRAN rather than to MRAN.  The reasons for doing this were discussed on other repos (hintr, at least, probably others) and this fix will be required on those repos too.  I see at least:
* naomi
* hintr
* rrq
* pointr
> VIMC-3610: Write entire Rprofile.site

- DESCRIPTION
- R/query_search.R
- tests/testthat/test-query-search.R
Previously this listed all directories in drafts, including those that failed (and therefore do not have an orderly_run.rds).  This PR skips those which lets the query actually complete in the face of failed drafts
> vimc-3620: Skip failed draft on search

- DESCRIPTION
- R/config.R
- R/main.R
- R/recipe_commit.R
- R/recipe_run.R
- R/util.R
- orderly.Rproj
- tests/testthat/test-run.R
- tests/testthat/test-util.R
This PR will
* Add support for `orderly_run` and `orderly_commit` to write logs to a `orderly.log` file based on a config flag
* Use config flag in CLI run
> VIMC-3617: Add support for redirecting orderly logs to a file

- DESCRIPTION
- R/develop.R
- R/orderly_recipe.R
- R/recipe_run.R
- tests/testthat/test-develop.R
- tests/testthat/test-orderly-recipe.R
- tests/testthat/test-run.R
Fixes two bugs I introduced in #197 - annoyingly these were both visible as a NOTE in the R CMD check output!  Added a test for each.
> VIMC-3641: fixes two unbound variable failures

- DESCRIPTION
- R/develop.R
- tests/testthat/test-db.R
- tests/testthat/test-develop.R
As reported by @sangeetabhatia03, when running a report as:
```
orderly::orderly_run("src/name/")
```
with a trailing slash there is a foreign key error because we save the wrong name (`name/`) into the orderly_run.rds and then try to write that into db, which fails with a foreign key constraint.
Likely a regression since moving to use `orderly_develop_location` for identifying the report name.  While this affects orderly_run.rds, no need for a data migration because the import fails.
> VIMC-3625: Cope with trailing slash on report name

- DESCRIPTION
- NEWS.md
- R/main.R
- R/util.R
- tests/testthat/test-main.R
This PR lets us accept batch parameters via a csv file like
```
orderly batch --file=parameters.csv
```
This is not super useful for most of the vimc/montagu use cases, but will be in the ncov work.  We can extend this interface to accept other parameters in future (json being an obvious one).
> VIMC-3660: Extend the batch cli interface to accept file input

- vignettes/orderly.Rmd
use colon instead of equals sign to separate keys and values.
> Fixed example of setting variables through orderly_envir.yml

- DESCRIPTION
- NEWS.md
- R/develop.R
- tests/testthat/test-develop.R
- vignettes/orderly.Rmd
As reported by @sangeetabhatia03 in #214, this PR fixes a bug and allows `orderly::orderly_develop_start()` to use environment variables declared in `orderly.yml` and defined in `orderly_envir.yml`
> vimc-3669: Allow environment variable setting in develop mode

- DESCRIPTION
- R/slack.R
- tests/testthat/test-slack.R
This PR uses backticks around the report name so that it doesn't get munged by Teams (see image below). This might look slightly worse in the Slack version, as the quotes will come through, so there's a switch there to keep the old behaviour in slack.
> vimc-3694: Escape underscores in report name

- DESCRIPTION
- NEWS.md
- R/db.R
- R/paths.R
- tests/testthat/test-db.R
This would have been useful with the published problem as reported by Kim, but might be useful generally going forward (and the cost is low).  Uses the already-tested backup db that uses the "proper" way of backing up a SQLite database.
> vimc-3702: Backup before rebuild

- DESCRIPTION
- R/query.R
- tests/testthat/test-query.R
This causes all sorts of breakage, and should be very rare.  Seen when launching orderly_run in parallel, which is something we'll have to think about properly at some point
> vimc-3783: Never allow multiple ids through

- DESCRIPTION
- R/recipe_commit.R
- R/util.R
- man/orderly_commit.Rd
- tests/testthat/test-db.R
- tests/testthat/test-util.R
This PR solves one of a couple of problems with running orderly in parallel - if multiple jobs try to write to the DB at once it can lead to errors as they can't get a write lock (this is problematic with the way we do the whole db addition as one atomic commit within a transaction).  I've added an exponential backoff here to try and address this.  It's awful to test and the implementation also relies on an error string in the RSQLite sources
> VIMC-3781: Avoid database locking problems in parallel

- .Rbuildignore
- DESCRIPTION
- NEWS.md
- R/orderly_recipe_depends.R
- R/paths.R
- R/query.R
- R/query_search.R
- R/remote.R
- R/remote_path.R
- man/orderly_pull_dependencies.Rd
- man/orderly_search.Rd
- tests/testthat/test-deduplicate.R
- tests/testthat/test-main.R
- tests/testthat/test-query-search.R
- tests/testthat/test-remote-path.R
- tests/testthat/test-remote.R
This PR allows pulling of reports based on a query (so rather than `latest`, we might pull on `latest(parameter:x == 1)`), as noticed by @lwhittles on the ncov work.
> VIMC-3789: Allow pulling based on query dependency

- DESCRIPTION
- NEWS.md
- R/util.R
- docker/build_website
- tests/testthat/test-run.R
This PR allows the error thrown in a failed orderly run to be recorded in the logfile - currently it is only printed to screen.  This has proved quite annoying in parallel runs. We also print the traceback here too
> Capture error in failed run

- DESCRIPTION
- R/db2.R
Forgot to bump this during #234 so currently user is not prompted to run `orderly::orderly_rebuild()` to fix `workflow` tables not existing.
> Bump orderly schema version number

- DESCRIPTION
- NEWS.md
- R/git.R
- R/runner.R
- R/util.R
- tests/testthat/test-git.R
- tests/testthat/test-util.R
- tests/testthat/test-z-runner.R
This PR will
* Add a function `git_commits` to orderly_runner which takes parameter branch which if master returns the last 25 commits, otherwise returns the commits not merged into master (limit 25)
Do we want to limit to return last 25 commits or limit based on some time period instead?
> VIMC-3941: Add orderly support for returning git commit info

- DESCRIPTION
- NEWS.md
- R/git.R
- R/runner.R
- R/util.R
- tests/testthat/test-git.R
- tests/testthat/test-util.R
- tests/testthat/test-z-runner.R
Couple of things to note here this follows on from #241
This fixes a bug in #241 and adds a test for it. I've left that in here as the test which recreates it is wrapped up with some testing of the feature added here. But I can separate out if you prefer.
> VIMC-3945: Add orderly support for listing available reports for a particular git branch and commit

- DESCRIPTION
- NEWS.md
- R/git.R
- R/runner.R
- tests/testthat/test-git.R
- tests/testthat/test-z-runner.R
Diff here noisy again as this builds on #242
Plan here is to return as a parsed list without any further processing. Then do the conversion from this list representation into the format we want to return from the endpoint in orderly.server
One thing to note is that I see there is an old format for the parameters
```
parameters:
- param1
- param2
```
Which is deprecated but still supported - there is some conversion code around. This currently doesn't support that but if we want to then I should probably do the conversion from the migration step here before returning it to orderly.server.
> VIMC-3953: Add function to get parameters for a report at a commit id

- DESCRIPTION
- NEWS.md
- R/new.R
- tests/testthat/test-new.R
Allows `orderly::orderly_new()` to work when src/ is entirely missing. Reported in the ncov work. Obviously not a very common situation, but it's an obscure enough error message:
```
> orderly_new("test", root = path)
Error in file_copy(template, dest_yml) : Error copying files
In addition: Warning messages:
1: In dir.create(dest) :
cannot create dir '/private/var/folders/z7/c2kx_kt96zn2tt_6179bkc4m0000gp/T/RtmpLrWlCi/file5964278f5e38/src/test', reason 'No such file or directory'
2: In file.create(to[okay]) :
cannot create file '/private/var/folders/z7/c2kx_kt96zn2tt_6179bkc4m0000gp/T/RtmpLrWlCi/file5964278f5e38/src/test/orderly.yml', reason 'No such file or directory'
```
> vimc-4032: Allow orderly_new to work when src is missing

- docker/Dockerfile
- docker/Rprofile.site
XML is not installing, causing other packages not to install, as it is the first thing to declare a dependency on 4.0.0 or more. I think that we're probably ok to upgrade now it's been out for a couple of months, though I think it breaks stan (we don't use that anywhere, and stan is a fragile thing to get running anyway unfortunately)
> vimc-4131: Upgrade R

- DESCRIPTION
- NEWS.md
- R/orderly_version.R
- tests/testthat/test-run.R
Long title, short fix. We were not allowing parameters to use their default values in resolving dependencies. From the ticket:
if we have a report A with parameters x and a report B that uses it and has parameter y, and depends like:
```
latest(parameter:x == y)
```
then the query will fail unless the parameter is passed explicitly (i.e., the default is ignored)
This was/is affecting a few ncov reports
> vimc-4135: Correct handling of parameter value defaults in dependency resolution

- DESCRIPTION
- NEWS.md
- R/orderly_version.R
`file.rename()` is not valid across filesystems, and that's the situation here when orderly is running in a container in orderlyweb.
Unfortunately, the default R behaviour here is to warn and continue, so have used fs functions instead. I've opened VIMC-4357 to move all the base file functions over (after talking with Jenny Bryan, I'm motivated to do this)
> vimc-4354: Don't use file.rename when it may cross filesystems

- DESCRIPTION
- NEWS.md
- R/bundle.R
- tests/testthat/test-bundle.R
Currently we assume filename is of form `<id>.zip` which will not be the case in (say) orderly.server. This PR relaxes this and works out the filename from the file itself.
> vimc-4382: Allow orderly_bundle_import to work with arbitrary filename

- DESCRIPTION
- NEWS.md
- R/develop.R
- R/remote.R
- tests/testthat/test-develop.R
See VIMC-4485 for an issue about renaming the internal function here.
Fixes #260
> Sanitise name for orderly_pull_archive

- DESCRIPTION
- NEWS.md
- R/query_search.R
- R/remote.R
- man/orderly_pull_dependencies.Rd
- tests/testthat/helper-orderly.R
- tests/testthat/test-query-search.R
- tests/testthat/test-remote.R
This PR will:
* Construct a default query from parameters if `id = "latest"`
* Update docs to hopefully make this behaviour clear
> Make orderly_pull_archive parameter arg more behaviour more predictable

- DESCRIPTION
- R/util.R
- tests/testthat/test-remote-path.R
- tests/testthat/test-util.R
This PR will
* Not save `output.log` with colour encoding
* Strip it elsewhere where it was causing test failures
> Don't save output with colour and strip colour codes from testing

- DESCRIPTION
- NEWS.md
- R/query.R
- R/query_search.R
- man/orderly_latest.Rd
- tests/testthat/test-orderly-recipe.R
- tests/testthat/test-query.R
Addresses #259 
The issue in #259 was because resolving dependencies can take e.g. `draft = "newer"` which works with finding the report in `orderly_find_report` and searching in `orderly_search` but it doesn't work when checking if the report we found is the latest report using `orderly_latest`. To fix I have added support to `orderly_latest` to take draft `newer`, `always` or `never`.
> VIMC-4579: Enable orderly_latest to find latest from draft or archive

- .github/workflows/R-CMD-check.yaml
- .github/workflows/test-coverage.yaml
- DESCRIPTION
- NEWS.md
- R/cleanup.R
- R/develop.R
- R/file_store.R
- R/util.R
- tests/testthat/helper-orderly.R
- tests/testthat/test-cleanup.R
- tests/testthat/test-util.R
* This will now print out how many draft reports, csv files and rds files are going to be deleted
* And sanitise report name before running cleanup (i.e. strip / and strip preceeding `src`)
I think this should address #265
> VIMC-4580: Make orderly_cleanup chattier and sanitise report name

- DESCRIPTION
- R/testing.R
- man/orderly_example.Rd
- tests/testthat/test-testing.R
This PR adds an argument `git` which allows creation of an empty git repo within a demo directory. Needed for working with orderly.server
> vimc-4608: Add support for creating a git repository

- DESCRIPTION
- R/testing.R
- man/orderly_example.Rd
- tests/testthat/test-testing.R
In an effort to nail down the montagu deploy, this PR adds even more git support to example repos that need it. It copies code from orderly.server, which we are pretty certain works with OrderlyWeb in tests
> VIMC-4611: More comprehensive git setup

- DESCRIPTION
- NEWS.md
- R/orderly_version.R
- R/paths.R
- tests/testthat/test-bundle.R
- tests/testthat/test-main.R
- tests/testthat/test-run.R
This will save out failure rds from
* orderly_run
* orderly_run_internal
* bundle_run - I assume this is useful? but this will just exist in the working dir
> VIMC-4037: Save orderly_fail.rds when report run is unsuccessful

- DESCRIPTION
- NEWS.md
- R/dependencies.R
- R/dependencies_src.R
- man/orderly_graph.Rd
- tests/testthat/test-dependency.R
> MRC-2321: max-depth arg to orderly_graph now limits depth of tree returned

- DESCRIPTION
- R/db2.R
- docker/Dockerfile
- inst/database/schema.yml
- tests/testthat/test-db.R
Does this need any migration test? I think the specific migration tests are for migrations to the archive? But here this is just db update which will be managed automatically by running `orderly_rebuild` I believe?
> Add report_version_instance table to store info about db instances report ran against

- DESCRIPTION
- R/testing.R
- inst/init/gitignore
This is a helper used by orderly.server, the gitignore was saved as `gitignore` instead of `.gitignore` so wasn't being used. Also added `/runner` dir to gitignore which gets created by orderly.server
> Fix gitignore in orderly git example

- DESCRIPTION
- NEWS.md
- R/remote.R
- tests/testthat/test-dependency.R
Previously:
```
orderly_pull_dependencies("use_dependency", parameters = list(x = 0.05),
remote = remote, root = path_local)
Error: Version 'NA' not found at '/tmp/RtmpVm93uq/file2496161bcdf2': valid versions are:
- 20210506-085109-de7f0302
- 20210506-085110-419fde6e
- 20210506-085110-7a8cd960
```
which is a problem because you don't even know what report it failed on, and the version information is no use. Now we get:
```
Error: Failed to find suitable version of 'other' with query:
'latest(parameter:nmin < x)'
and parameters
- x: 0.05
```
Better would be to find "close" parameter matches but that's nontrivial
> Much clearer error message on query failure

- DESCRIPTION
- R/testing.R
- inst/init/gitignore
This PR will
* Add `backup` to gitignore file
* Use this in `build_git_demo` adding additional lines only needed for testing
Not ideal that there are `orderly.server` specific things bleeding into the repo setup here but keen to get in a fix as this is blocking front end tests running on buildkite and there is already `orderly.server` specific things in the `gitignore`
> mrc-2416: Add backup to gitignore

- R/info.R
- R/orderly_version.R
- tests/testthat/test-run.R
See previous discussion https://github.com/vimc/orderly/pull/273#discussion_r581923674
It looks like it is less disruptive to remove git from `meta$git` and only have it at path `git`, but happy to move if we think it fits beta as `meta$git`
> Remove git info from metadata to avoid dupe info

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- NEWS.md
- R/orderly_recipe.R
- tests/testthat/test-run.R
See failing build for 778fc3f which replicates an issue that I could see on 3.6 locally. Different to the commit error, but I could not reproduce that (and had issues installing 3.6 into docker due to binary incompatibilities)
Version number set to merge after #294
> Add oldrel and 3.6 builds

- DESCRIPTION
- NEWS.md
- R/orderly_recipe.R
- tests/testthat/test-run.R
As reported by @jeffeaton, this errors on scripts that use `rm(list = ls())` or similar. If this is to annoying we could hide this behind an option, though it's hard to immediately see a good reason to allow it.
> Prevent use of rm(list = ls()) in scripts

- DESCRIPTION
- R/bundle.R
- tests/testthat/test-bundle.R
This is temporary, and we may not merge it depending on how the fix to zip goes (see https://github.com/r-lib/zip/pull/79)
Let's merge for now and remove once zip is updated on CRAN
> Workaround for zip_list on large files

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- R/bundle.R
- R/util.R
- docker/Dockerfile
- tests/testthat/helper-orderly.R
- tests/testthat/test-run.R
- tests/testthat/test-util.R
This PR fixes the current failing builds here: https://cran.r-project.org/web/checks/check_results_orderly.html
My belief as to what is going on is in the comment in test-run.R: knitr now requires that anyone knitting a markdown (rather than sweave) document includes the dependency on `markdown` even though that is clearly a knitr dependency (see https://github.com/yihui/knitr/issues/1864), then there's a workaround for this unfortunate decision in knitr which seems to break our package (https://github.com/yihui/knitr/commit/9a80a00). However, this breaks *differently* on CRAN machines and ours because this workaround tries not to error and instead silently writes an empty file, so the test fails.
Having updated things to include knitr's dependency among ours (as I guess hundreds of …
> Fix reported CRAN check failure

- DESCRIPTION
- NEWS.md
- R/deduplicate.R
- R/logging.R
- R/remote.R
- R/util.R
- README.md
- man-roxygen/example-remote.R
- man/orderly_deduplicate.Rd
- man/orderly_log.Rd
- man/orderly_pull_dependencies.Rd
- man/orderly_remote_path.Rd
- tests/testthat/test-run.R
- tests/testthat/test-util.R
- vignettes/orderly.Rmd
- vignettes/patterns.Rmd
- vignettes/remote.Rmd
Small QA things seen on win builder (https://win-builder.r-project.org/z4Ye9MEJqD0r/00check.log)
```
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Rich FitzJohn <rich.fitzjohn@gmail.com>'
Found the following (possibly) invalid URLs:
URL: https://en.wikipedia.org/wiki/Hash_function
From: inst/doc/orderly.html
README.md
Status: Error
Message: Failed to connect to en.wikipedia.org port 443: Timed out
...
* checking R code for possible problems ... [22s] NOTE
orderly_pull_metadata: no visible binding for global variable
'parameters'
Undefined global functions or variables:
parameters
```
* removed wikipedia links, which is a pity. We can add it later but it will hold things up if it's flakey, or risk the package being pulled at the same time it grinds through a manual review even …
> Small tweaks noticed on win builder

- DESCRIPTION
- R/testing.R
- inst/create_orderly_demo.sh
This simplifies the orderly test setup for OrderlyWeb
The `demo` dir will contain an orderly root with git and with reports have use dependencies `use_dependency` and `use_dependency_2`
> Update orderly demo script to include dependency reports in git example

- DESCRIPTION
- R/deduplicate.R
- docker/build_website
- tests/testthat/test-deduplicate.R
I've put this error in as soon as we list the paths to fail early. And not removed the 
```
stopifnot(all(vlapply(split(files, files$hash), function(x)
all(x$inode_first == x$inode[[1]]))))
```
which is what Oli has been seeing error previously. I can remove it if you think no longer relevant
> Return more informative error from deduplication

- DESCRIPTION
- inst/examples/demo/src/default-param/README.md
- inst/examples/demo/src/default-param/orderly.yml
- inst/examples/demo/src/default-param/script.R
Requested by @LekanAnni for testing something in orderly web. Atm there is no demo report with a default parameter.
I've checked this doesn't affect any of the orderly.server tests
> Add an example report to orderly demo which includes a default parameter

- R/batch.R
- R/main.R
- man/orderly_batch.Rd
- tests/testthat/examples/batch/src/example/orderly.yml
- tests/testthat/examples/batch/src/example/script.R
- tests/testthat/examples/workflow/source.R
- tests/testthat/examples/workflow/src/example/orderly.yml
- tests/testthat/examples/workflow/src/example/script.R
- tests/testthat/examples/workflow/workflows/broken_steps.yml
- tests/testthat/examples/workflow/workflows/missing_name.yml
- tests/testthat/examples/workflow/workflows/missing_report.yml
- tests/testthat/examples/workflow/workflows/missing_steps.yml
- tests/testthat/test-batch.R
- tests/testthat/test-db.R
- tests/testthat/test-main.R
This will
* Update output from `orderly_batch` from a vector of ids to a data frame e.g.
```
id, success, param1, param2
123, TRUE, 0, "a"
456, FALSE, 0.2, "b"
```
* Add an arg to `orderly_batch` `continue_on_error` which is TRUE by default which will run subsequent reports if any in the batch run fail. Still errors early if it fails during preparation (before the report ID is available)
* Removes an old test setup for `workflow` which is no longer used
I couldn't decide if it would be better to continue from all errors and return e.g.
```
id, success, param1, param2
NA, FALSE, 0, "a"
NA, FALSE, 0.2, "b"
```
if they fail before the report ID is available. I think if 1 report fails before the report ID is available it is likely that all the others will too. If they fail during preparation …
> vimc-4875: Add mode to batch run to continue on failure

- DESCRIPTION
- R/new.R
- man/orderly_new.Rd
There seemed to be a small error in the documentation. It said templates should go in the "templates" directory, but `has_template()` actually looks in the __template__ directory.
> Fix documentation for where to store templates

- DESCRIPTION
- R/db2.R
- inst/database/schema.yml
Comment 2020: This removes the last bit of the pre-proper-schema orderly db - adding custom fields to the report_version table.  The schema version number increases (which triggers a db rebuild) but this should have minimal visibility to users.
This should be tested on uat with montagu pointing at this version to make sure nothing breaks.
Comment 2022: This has to be merged/deployed in lock step with https://github.com/vimc/orderly-web/pull/476 (and waiting for OW master build to be fixed before that build can pass!) Then will need to rebuild `orderly.server`.
> VIMC-2929: Remove custom fields from main orderly table
